repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-imports
      - id: go-cyclo
        args: [-over=15]
      - id: validate-toml
      - id: no-go-testing
      - id: golangci-lint
      - id: go-critic
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-staticcheck
      - id: go-sec
      - id: go-vulncheck
      - id: go-vet-mod
      - id: go-revive
        args: [-config=.revive.toml]

  - repo: local
    hooks:
      - id: go-test-coverage
        name: Go Test Coverage
        entry: bash -c 'go test -race -coverprofile=coverage.txt -covermode=atomic ./... && go tool cover -func=coverage.txt'
        language: system
        types: [go]
        pass_filenames: false

ci:
  autofix_commit_msg: "ci: auto fixes from pre-commit hooks"
  autoupdate_commit_msg: "ci: pre-commit autoupdate"
  skip: []
