# Default values for hashicorp-vault-migrations.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hashicorp-vault-migrations
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

# Vault connection configuration
vault:
  enabled: true
  address: ""
  token: ""
  namespace: ""
  skipVerify: false
  # Existing secret containing Vault token
  existingSecret: ""
  tokenKey: "token"

# Migration configuration
config:
  logLevel: info
  logFormat: json
  # Schema configuration
  schema:
    # ConfigMap containing schema.yaml
    configMap: ""
    key: "schema.yaml"

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  fsGroup: 65532

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# CronJob configuration for periodic migration checks
cronJob:
  enabled: false
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  backoffLimit: 3
  activeDeadlineSeconds: 600
  restartPolicy: OnFailure

# Vault server configuration (from dependency)
vault:
  server:
    dev:
      enabled: true
    standalone:
      enabled: false
    ha:
      enabled: false
  injector:
    enabled: false
